// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package toyrobot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_PUSH_VAL-0]
	_ = x[OP_EXEC_WORD-1]
}

const _Instruction_name = "OP_PUSH_VALOP_EXEC_WORD"

var _Instruction_index = [...]uint8{0, 11, 23}

func (i Instruction) String() string {
	if i >= Instruction(len(_Instruction_index)-1) {
		return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instruction_name[_Instruction_index[i]:_Instruction_index[i+1]]
}
