// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package toyrobot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKEN_PLACE-0]
	_ = x[TOKEN_MOVE-1]
	_ = x[TOKEN_LEFT-2]
	_ = x[TOKEN_RIGHT-3]
	_ = x[TOKEN_REPORT-4]
	_ = x[TOKEN_NUMBER-5]
	_ = x[TOKEN_COMMA-6]
	_ = x[TOKEN_DIRECTION-7]
}

const _TokenType_name = "TOKEN_PLACETOKEN_MOVETOKEN_LEFTTOKEN_RIGHTTOKEN_REPORTTOKEN_NUMBERTOKEN_COMMATOKEN_DIRECTION"

var _TokenType_index = [...]uint8{0, 11, 21, 31, 42, 54, 66, 77, 92}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
