// Code generated by "stringer -type=RobotType"; DO NOT EDIT.

package toyrobot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_INT-0]
	_ = x[T_DIRECTION-1]
}

const _RobotType_name = "T_INTT_DIRECTION"

var _RobotType_index = [...]uint8{0, 5, 16}

func (i RobotType) String() string {
	if i >= RobotType(len(_RobotType_index)-1) {
		return "RobotType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RobotType_name[_RobotType_index[i]:_RobotType_index[i+1]]
}
